# Generated by Django 2.0.5 on 2019-02-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='slack_channel',
        ),
        migrations.AddField(
            model_name='company',
            name='slack_webhook',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
