# Generated by Django 2.1.7 on 2019-02-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_admin', '0002_auto_20190212_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('menu', models.ManyToManyField(to='menu_admin.Menu')),
            ],
        ),
    ]
